"use client"
import './globals.css'
// import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes';
import localFont from "next/font/local";

// const dirtyline = localFont({src: "../../fonts/dirtyline.ttf"})
const aeonik = localFont({src: "../../fonts/Aeonik-Regular.ttf"})

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FFF8F8] dark:bg-[#121212] scrollbar-hide" style={aeonik.style}>
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
